### ISSUE TITLE
Indentation Levels

### ISSUE THREAD

**Issue by jim-rosales** [86highlander/tea_cozy#4]
Your indentation seems a little off. Take a look at this [HTML](https://gist.github.com/jim-rosales/46f2f87823e2546e3e1da4427e72bb48) solution to compare and contrast your indentation with the solutions. 

Having correct indentation improves the overall readability of your code which is helpful when working in teams. 

https://github.com/86highlander/tea_cozy/blob/726be0b8699b048e97feff1062230e69bed1072a/index.html#L24-L98

**Comment by 86highlander** [comment]
I did struggle a little with the indentation levels. Atom seems not always to automatically apply  - I know I need to be diligent. Thx for the input.
