### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [86highlander/tea_cozy#5]
Grade: Meets Expectations

Summary: 
Trevor, fantastic job on the Tea Cozy project! Overall you did an excellent job both syntactically and structural as I did not see any issues with your project! Apart from this, they were both very easy to read considering you commented both so congrats on that!

I do suggest you look at issue #4 a bit more in-depth as indentation does provide a key role in improving the readability of your HTML just how like comments do.

If you'd like to hone your CSS skills a bit more I suggest you read into [hover effects](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover), [transitions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions), and [variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables). Both transitions and hover effects are frequently used to provide visual cues and feedback. This [codepen](https://codepen.io/JacobStone/pen/GfLEn) showcases how both can be used to add some neat features in a site. 

Variables, on the other hand, are a great tool that allows you to both increases the readability of a file and how responsive it is to future changes.

**Comment by 86highlander** [comment]
Thx for the feedback. Noted about hover and transitions. I read ahead on the second just yesterday. Will read #4 about indentation in detail.
